on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

name: tag-and-release
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      JRELEASER_GITHUB_TOKEN: ${{ secrets.BREW_GITHUB_TOKEN }}
      JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
      JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.OSSRH_USERNAME}}
      JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      JRELEASER_VERSION: 1.19.0
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - name: install-java11
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - name: gradle-build-and-release
        run: ./gradlew --no-daemon --build-cache --scan -s clean publish jreleaserRelease
      - name: release-output
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: upload-release-output
          path: |
            build/reports
            build/jreleaser/trace.log
            build/jreleaser/output.properties
